language: node_js
node_js:
  - '16'
cache:
  directories:
    - node_modules
    - ~/.npm
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Project deployment"
  on:
    branch: main